### ISSUE TITLE
Enhance quickstart instructions in README.md

### ISSUE THREAD

**Issue by olisteadman** [gajus/swing#139]
Not clear how to run locally, e.g. whether using `node index.js` (gives me errors) or similar.

```
➜  src git:(master) node index.js 
/Users/oliversteadman/_Tuts/swing/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import Card from './Card';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by gajus** [comment]
Too broad of a question. Basic knowledge of the ecosystem is required.
