### ISSUE TITLE
gulp build-browser - SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by gojohnnygo** [gajus/swing#54]
I'm looking to add swipe top and bottom functionality.

I've added code to src, when I try to `gulp build-browser` while in the `bower-components/swing` folder of my project, I get a `SyntaxError: Unexpected reserved word` on "import" from `import gulp from 'gulp'`.

Do you know what's happening here? What's the best way to test edits before a PR?

Cheers,
Johnny

**Comment by gajus** [comment]
```sh
babel-node ./node_modules/.bin/gulp build-browser
```

**Comment by gojohnnygo** [comment]
Sorry if I'm being dense, but I'm getting an error.

1. `npm install --global babel-cli`
2. `yo gulp-webapp`
3. `bower install swing -S`
4. `gulp wiredep`
5. `babel-node ./node_modules/.bin/gulp build-browser` > ERROR
```
/Users/johnny.nguyen/Projects/swing/gulpfile.babel.js:2
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/Users/johnny.nguyen/.nvm/versions/node/v4.2.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/johnny.nguyen/.nvm/versions/node/v4.2.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/Users/johnny.nguyen/Projects/swing/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/johnny.nguyen/Projects/swing/node_modules/gulp/node_modules/liftoff/index.js:192:16)
```

**Comment by gajus** [comment]
```sh
git clone git@github.com:gajus/swing.git
cd ./swing
npm install
node ./node_modules/.bin/babel-node ./node_modules/.bin/gulp build-browser
```

works fine.

**Comment by gojohnnygo** [comment]
Thanks, the above works. I was trying to make edits to source while in the context of my project, but this will do. 

:+1:
